### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by daanbonke** [shagstrom/split-pane#10]
When I try to drag a `.fixed-left` it shows this error in the developers console 
The error is on this line: `jQuery.event.handle.apply(element, arguments);`

This is because I'm using the latest version of jQuery and handle is deprecated/removed in that version. Instead I tried to do `jQuery.event.dispatch.apply(element,arguments);` 
This however gives a result that the dragging isn't smooth.

**Comment by shagstrom** [comment]
I'm not experiencing this with jQuery 1.11.2 or 2.1.3. What versions of jQuery and browsers are you using? Can you also show me your code?
