### ISSUE TITLE
Typo on line 82 + tips for triggering layout refresh after manually setting new width?

### ISSUE THREAD

**Issue by kdmon** [shagstrom/split-pane#11]
Nice library. I think I spotted a typo on line 82:
` $(document).one(endEvent, function(event) {`
Should be on(), not one().

By the way, is there an easy way to trigger a refresh after manually setting a new pane width (other than  simulating a mousemove or calling/refactoring createMousemove())? For example, I have a button which should minimise a vertical pane when clicked:

```javascript
$("#toggle-pane-left").on("click", function () {
  $("#left-component").width(0);
  $("#first-divider").css("left", 0);
 // insert function call here to update layout
});
```

Thanks

**Comment by shagstrom** [comment]
First, $(document).one(...) is not a typo. It's documented here http://api.jquery.com/one/ .

Second, you need to set right component left, too.

    $("#right-component").css("left", 0);

Then you can trigger the internal _splitpaneparentresize event.

    $("#left-component").closest('.split-pane').trigger('_splitpaneparentresize');

**Comment by kdmon** [comment]
Ah, my bad. I live and learn. Triggering  ```_splitpaneparentresize``` work beautifully! Thank you for a great library and support! I've updated the issue topic to reflect my main question.
