### ISSUE TITLE
Should not unbind foreign event handlers

### ISSUE THREAD

**Issue by asten7** [shagstrom/split-pane#12]
Hello and thanks for a great plugin!

I found out that other components that bind the documents resize event stop working after having dragged the splitter. I believe this is because in the mouseDownHandler all resize event handlers are unbound, not just the one split-pane registered:			

    $(document).unbind(moveEvent);

One possible solution would perhaps be to use namespaces when binding and unbinding events?

Regards
Andreas

**Comment by shagstrom** [comment]
Thanks for reporting this!

I has been fixed in v0.4.1.

**Comment by asten7** [comment]
Thanks! It seems to be working now.
