### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by WC1437** [shagstrom/split-pane#17]
I am getting the error "Cannot read property 'offsetWidth' of undefined". This happens when using the basic setup code noted in the README  (div class="split-pane fixed-left".. div class="split-pane-component" id="left-component"..div class="split-pane-divider" id="my-divider"/div..div class="split-pane-component" id="right-component"; and following the other styling provided).  

The error is focused on line 133 of the split-pane.js file: 
var maxFirstComponentWidth = splitPane.offsetWidth - lastComponentMinWidth - divider.offsetWidth;

I have experimented with the other settings (percentage-left, fixed-top, etc...) and the error occurs there are also. I am using jQuery in Rails, but I doubt that makes a difference. jQuery 1.11.

This error seems to occur if (i) there is anything at all at the top of the body above were the "split-pane fixed-left" line appears--even if it is not anything visible to user but just an empty div class, or (ii) there are any divs in between "split-pane fixed left" and "split-pane-component" id="left-component"...even if these divs have nothing in them. I am putting in these extra divs so I can grab on to them with jquery and add in the split pane classes as wrappers for those divs upon certain events happening, so I would like to keep those divs.

**Comment by shagstrom** [comment]
The only structure that works is

    <div class="split-pane">
        <div class="split-pane-component">...</div>
        <div class="split-pane-divider">...</div>
        <div class="split-pane-component">...</div>
    </div>

Anything else won't be allowed. That is you can't add extra elements in between, only inside split-pane-component.

**Comment by WC1437** [comment]
Got it. Thanks. And thanks for the very helpful plug-in.
