### ISSUE TITLE
changing the divider width

### ISSUE THREAD

**Issue by mikagenic** [shagstrom/split-pane#18]
I'm not able to change the divider width. For example in percent-vertical.html in
	#my-divider {
		right: 80%;
		width: 5px;
	}

I tried to change width to 1px but it did not seem to have any effect.
Any help ?

**Comment by shagstrom** [comment]
Did you change left-component margin-right too? It needs to be 1px too.


    #left-component {
        right: 50%;
        margin-right: 5px;
    }

**Comment by mikagenic** [comment]
got it thx
