### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by newghost** [shagstrom/split-pane#23]
$layoutRightPane.splitPane('lastComponentSize', 240)

There is an error :

![ie8mode_issue](https://cloud.githubusercontent.com/assets/1529044/12016017/aa1891e6-ad80-11e5-87b4-a0323510dbac.png)

**Comment by newghost** [comment]
function setLeft(firstComponent, divider, lastComponent, left) {
		firstComponent.style.width = left;
//Invalid argument.  left is NANpx
		divider.style.left = left;
		lastComponent.style.left = left;
	}

**Comment by shagstrom** [comment]
The issue has been fixed in 0.7.1.
