### ISSUE TITLE
window resize doesn't work for fixed-right

### ISSUE THREAD

**Issue by newghost** [shagstrom/split-pane#24]
This code doesn't work for fixed-right pane, and fixed-left works fine.

    $(document).on('resize', function() {
      console.log('resized')
    }).trigger('resize')

I comments this line for work around
event.stopPropagation();

	/**
	 * A special event that will "capture" a resize event from the parent split-pane or window.
	 * The event will NOT propagate to grandchildren.
	 */
	$.event.special._splitpaneparentresize = {
		setup: function(data, namespaces) {
			var element = this,
				parent = $(this).parent().closest('.split-pane')[0] || window;
			$(this).data(SPLITPANERESIZE_HANDLER, function(event) {
				var target = event.target === document ? window : event.target;
				if (target === parent) {
					event.type = "_splitpaneparentresize";
					$.event.dispatch.apply(element, arguments);
				} else {

					//event.stopPropagation();
				}
			});
			$(parent).on('resize', $(this).data(SPLITPANERESIZE_HANDLER));
		},
		teardown: function(namespaces) {
			var parent = $(this).parent().closest('.split-pane')[0] || window;
			$(parent).off('resize', $(this).data(SPLITPANERESIZE_HANDLER));
			$(this).removeData(SPLITPANERESIZE_HANDLER);
		}
	};

**Comment by shagstrom** [comment]
Thanks for reporting this! This has now been fixed in version 0.8.0.

**Comment by newghost** [comment]
Thank you, works fine.

    $(document).on('splitpaneresize', function() {

        //

    }).trigger('splitpaneresize')
