### ISSUE TITLE
how to catch pane resized event?

### ISSUE THREAD

**Issue by naivefun** [shagstrom/split-pane#25]
Is there an API for that? THanks.

**Comment by shagstrom** [comment]
Use latest version 0.8.0 and try:

    $('.split-pane').on('dividerdragstart', function (event, data) {console.log(data.firstComponentSize, data.lastComponentSize)})

    $('.split-pane').on('dividerdragend', function (event, data) {console.log(data.firstComponentSize, data.lastComponentSize)})
