### ISSUE TITLE
specify initial left pane width in pixels

### ISSUE THREAD

**Issue by kofifus** [shagstrom/split-pane#28]
Is it possible to specify the initial left pane width in pixels ?

I tried remarking 'right' in #left-component and #my-divider and replacing them with left:190px; but not sure how to change the 'width' in #right-component ?

thx!

**Comment by shagstrom** [comment]
If you want to set left component width it make most sense if you use fixed-left:

http://dreamchain.com/static/split-pane/fixed-left.html

Otherwise (using the latest version of split-pane) you can do this:

    $(selector).splitPane('firstComponentSize', 0);"

**Comment by kofifus** [comment]
fixed-left solved it thx!
