### ISSUE TITLE
how to add click event handler to pane-divider?

### ISSUE THREAD

**Issue by kkozlik** [shagstrom/split-pane#32]
I want to hide the pane when user click to the divider. But code like this does not work:

```
$( "#pane-divider" ).on('click', function(){
    $("#split-pane").splitPane('firstComponentSize', 0);"
});
```

The event handler is never reached. It seems the event propagation is stopped in your code.

**Comment by shagstrom** [comment]
Thanks for reporting this! A fix is now in version 0.9.3. I removed the resize shim, which should not be needed anymore after preventing default event on mousedown and mousemove. Can you please give it a try?

**Comment by kkozlik** [comment]
Thanks for the quick fix! The click event is propagated now. 

The only issue is that the event is raised even when I drag the pane. But well, I am not sure whether it is really a bug or a feature :-).

Do you have an idea how to distinguish the two cases (user just clicked or user dragged the pane divider) in the event handler?

**Comment by shagstrom** [comment]
Yes, it's a feature. I'm not disturbing the event propagation.

You can try something like this:

```
$('.split-pane-divider').on('mousedown', function () {
	var dragged = false;
	var resizeHandler = function () { dragged = true; }
	$('div.split-pane').on('splitpaneresize', resizeHandler);
	$('.split-pane-divider').one('mouseup', function () {
		$('div.split-pane').off('splitpaneresize', resizeHandler);
		if (!dragged) {
			console.log("click");
		}
	});
});
```

**Comment by kkozlik** [comment]
Thanks for the hint! It is working nicely now.
