### ISSUE TITLE
cursor is changing when drag panel divider

### ISSUE THREAD

**Issue by Unrasend** [shagstrom/split-pane#35]
Cursor twitches and changing style from col-resize to default when im dragging divider, especially it can be clearly seen in Internet Explorer 10/11.

It is problem of version 0.9.3. In 0.9.2 all is fine.

**Comment by shagstrom** [comment]
Ok, I did a fix related to the divider in 0.9.3. I'll have a look. Thanks for reporting!

**Comment by enough1987** [comment]
the same problem
